---

services:

  node:

    image: tugboatqa/node:8
    expose: 3000

    default: true

    commands:

      init:
        - mkdir -p /etc/service/node
        - echo "#!/bin/sh" > /etc/service/node/run
        - echo "cd ${TUGBOAT_ROOT} && node server.js" >> /etc/service/node/run
        - chmod +x /etc/service/node/run

